### ISSUE TITLE
Firebase integration

### ISSUE THREAD

**Issue by TimvdLippe** [WISVCH/connect#12]
This ticket is related to connect, but the solution project will likely be placed in a separate project. Since it needs some place to be tracked and it is related to connect, I think this is the correct place for now.

### Use case

Firebase offers interesting features that are ideal for the committee websites. Most notably it prevents the need for an API + database to run (e.g. we can just serve static content), we can log in anonymously (for external users) and we can have integration with other authentication services (such as CH connect for CH members). 

### Technical details

Firebase has an option [to log in with a token](https://firebase.google.com/docs/auth/web/custom-auth). This token must be a JSON Web Token with [a specific format](https://firebase.google.com/docs/auth/admin/create-custom-tokens). The format [returned by OpenID](http://openid.net/specs/openid-connect-core-1_0.html#IDToken) is almost equivalent to the required format, but with small changes. Therefore we need a service that takes the OpenID token returned by Connect and transform it a Firebase-compatible token.

### Possible solution

Firebase has several samples, including [an Instagram sample](https://github.com/firebase/custom-auth-samples/blob/6022d98265a549e91fdf457c7daab77a6ba94962/instagram/app.js) that looks very similar to our CH Connect. The solution would therefore write a node micro-service that connects with CH Connect, obtains the token etc... and then transform and serves the Firebase-compatible token.

### Concrete requirements

All in all, the integration has the following requirements:
1. Exposes an endpoint that a committee website can redirect to
2. On this endpoint the user is redirected to CH Connect (or in some way is authenticated with Connect)
3. The service transforms the token into a Firebase-compatible token
4. It returns (in JSON) the token.

CC @gijsweterings as you expressed interest in solving this problem :smile:

**Comment by praseodym** [comment]
This should indeed be a new project. I'd want to propose a slightly different approach with other requirements:
1. Log in with CH Connect on the website itself (redirect and acquire token)
2. XHR that token to the (to be developed) endpoint to exchange it for a Firebase token

For the first requirement, one would need to find a library to implement OIDC login to CH Connect; this should be plug-and-play. For the second requirement, one would need to implement OIDC authentication on the Firebase token exchange endpoint and implement all necessary functionality to create a Firebase token.

**Comment by GijsWeterings** [comment]
This second approach does seem like the better option, given that it would keep the door open for a secondary login flow that does not flow trough connect (for example a login option using the TUD SAML *shudder*). I'll try to whip something up in a new repo and link it!

**Comment by praseodym** [comment]
@GijsWeterings any progress on this?

**Comment by GijsWeterings** [comment]
I started on it, but @TimvdLippe mentioned that he needs to speak to Sven
about integration in events instead, so I put it on hold until I hear more

Op vr 3 mrt. 2017 om 15:53 schreef Mark Janssen <notifications@github.com>:
