### ISSUE TITLE
Missing CSRF token after consecutive login attempts

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/connect#16]
The CSRF token is missing for consecutive login attempts, causing it to fail.

To reproduce:
1. Login with CH Connect using (valid) TU Delft credentials
2. CH Connect rejects login attempt due to conflicting information in the CH database
3. Attempt to login with CH connect using (valid) CH credentials
4. 403 error: CSRF token is null

![chconnect_error](https://user-images.githubusercontent.com/579633/29824730-96b55e76-8cd2-11e7-875a-ff1b512370b0.PNG)

**Comment by praseodym** [comment]
Cannot reproduce in current version; please re-open if you can.
