### ISSUE TITLE
Subscriptions claim

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/connect#18]
Can / should we extend UserInfo with a mailings / Machazine subscriptions claim? Currently very useful for the website.

**Comment by praseodym** [comment]
What would you want to use it for?

**Comment by svenvanhal** [comment]
Expose the information on the CH website, allow users to change their preferences. Might be useful for other tools, but I think always in combination with Dienst2, so maybe the Dienst2 API is a better place for this.

**Comment by praseodym** [comment]
If you want to be able to change this preference (which makes sense) then integrating the Dienst2 API might be a better option.

**Comment by praseodym** [comment]
Using the Dienst2 API directly is preferred.
