### ISSUE TITLE
UserInfo omits preposition in family name

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/connect#19]
Currently, the user claim provides the following 'name' fields:

- name (e.g. "S. van Hal")
- preferred_username (e.g. "svenh")
- given_name => (e.g. "Sven")
- family_name => (currently: "Hal")

We should change family_name to "van Hal", or add an extra "preposition" field containing "van".

**Comment by praseodym** [comment]
Should we fix this in Connect or in the Dienst2 API?

**Comment by svenvanhal** [comment]
I believe this information is also useful for apps that do not use the Dienst2 API, so I think we should fix this in Connect.

**Comment by praseodym** [comment]
That's not the point here; if we fix it in the Dienst2 API it'll be fixed in Connect as well. But what's the best place to fix it?

**Comment by jgadelange** [comment]
I don't think there is anything broken in the Dienst2 API, since all the information is available there. Here the prepositions field is not available so I think it would best be stored in the family name

**Comment by praseodym** [comment]
We could extend the Dienst2 API with a new attribute, just like we also provide a full name attribute.
