### ISSUE TITLE
NestedServletException

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/connect#20]
See: https://github.com/WISVCH/website/issues/14. This happened while regularly logging in with valid credentials. We have been able to trace the error back to CH Connect (not the PHP implementation).

**Comment by praseodym** [comment]
Could you provide steps to reproduce this or provide an exact timestamp of when this occurred so that we can correlate that to any logging that might have been generated?

**Comment by praseodym** [comment]
Please re-open with a stacktrace or steps to reproduce.
