### ISSUE TITLE
NPE when member without Dienst2 birthday logs in

### ISSUE THREAD

**Issue by svenpopping** [WISVCH/connect#23]
Legacy members logging in at https://connect.ch.tudelft.nl will result in a NullPointerException, when fetching the user info.

Logs (userid has been replaced by XXXX):
```
INFO : org.mitre.openid.connect.web.AuthenticationTimeStamper - Successful Authentication of WISVCH.XXXX at Wed Feb 14 12:33:46 UTC 2018
DEBUG: ch.wisv.connect.overlay.services.CHUserInfoRepository - Loading user info for subject=WISVCH.XXXX
```

**Comment by praseodym** [comment]
Could you provide some more information?

**Comment by svenpopping** [comment]
More information provided above.

**Comment by svenpopping** [comment]
Guess I has to do something with the missing birthday of the member.
